# このファイルはインデントに注意
version: "3"
services:
  app:
    build:
      context: ./docker/php
      # Dockerファイルで使用
      args:
        - TZ=${TZ}
    volumes:
      - ./src:/work
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      # envの値を${環境変数名}でdocker-compose.ymlに受け渡しできる
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      # php.ini で使用
      - TZ=${TZ}